CREATE TYPE billing_interval_t AS ENUM ('monthly', 'yearly');
CREATE TYPE plan_status_t AS ENUM ('active', 'canceled', 'past_due');
CREATE TYPE payment_status_t AS ENUM ('succeeded', 'failed', 'pending');
CREATE TYPE ai_request_type_t AS ENUM ('feedback', 'suggestion', 'rewrite');
CREATE TYPE document_type_t AS ENUM ('general', 'social_media_post', 'creative_writing', 'article', 'report', 'email');
CREATE TYPE ad_event_type_t AS ENUM ('impression', 'click');

CREATE TABLE user_account (
    user_account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    telephone VARCHAR(20) UNIQUE,
    created_date TIMESTAMP NOT NULL,
    last_login_date TIMESTAMP NOT NULL
);

CREATE TABLE plan (
    plan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name VARCHAR(50) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL
);

CREATE TABLE plan_price (
    plan_price_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id INTEGER REFERENCES plan(plan_id),
    price DECIMAL(10, 2) NOT NULL,
        billing_interval billing_interval_t NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    effective_date TIMESTAMP NOT NULL,
    is_enabled BOOLEAN NOT NULL
);

CREATE TABLE feature (
    feature_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_name VARCHAR(50) NOT NULL UNIQUE,
    feature_description TEXT
);

CREATE TABLE plan_feature (
    plan_id INTEGER NOT NULL REFERENCES plan(plan_id),
    feature_id INTEGER NOT NULL REFERENCES feature(feature_id),
    is_enabled BOOLEAN NOT NULL,
    daily_limit INT NULL,
    monthly_limit INT NULL,
    PRIMARY KEY (plan_id, feature_id)
);

CREATE TABLE subscription (
    subscription_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id INTEGER REFERENCES user_account(user_account_id),
    plan_price_id INTEGER REFERENCES plan_price(plan_price_id),
    plan_start_date TIMESTAMP NOT NULL,
    plan_end_date TIMESTAMP NOT NULL,
    next_renewal TIMESTAMP NOT NULL,
    plan_status plan_status_t NOT NULL
);

CREATE TABLE payment (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id INTEGER REFERENCES subscription(subscription_id),
    amount DECIMAL(10, 2) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    payment_date TIMESTAMP NOT NULL,
    payment_status payment_status_t NOT NULL
);

CREATE TABLE document_setting (
    document_setting_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type document_type_t NOT NULL,
    target_audience VARCHAR(50) NOT NULL,
    tone VARCHAR(50) NOT NULL
);

CREATE TABLE document_metadata (
    document_metadata_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id INTEGER REFERENCES user_account(user_account_id),
    document_setting_id INTEGER REFERENCES document_setting(document_setting_id),
    created_date TIMESTAMP NOT NULL,
    last_modified_date TIMESTAMP NOT NULL,
    word_count INT
);

CREATE TABLE ai_request (
    ai_request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id INTEGER REFERENCES user_account(user_account_id),
    document_metadata_id INTEGER REFERENCES document_metadata(document_metadata_id),
    request_type ai_request_type_t NOT NULL,
    context_length INT NOT NULL,
    request_time TIMESTAMP NOT NULL
);

CREATE TABLE ad_impression (
    ad_impression_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id INTEGER REFERENCES user_account(user_account_id),
    event_type ad_event_type_t NOT NULL,
    impression_date TIMESTAMP NOT NULL
);
